import type { Metadata } from 'next';
import './globals.css';
import { Inter as FontSans } from 'next/font/google';
import ThemeProvider from '@/components/ui/theme-provider';

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Dharma',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.ico" sizes="any" />
      </head>

      <body className={fontSans.variable}>
        <ThemeProvider
          attribute="class"
          defaultTheme="purple"
          themes={['light', 'dark', 'system', 'purple']}
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
