import { Toaster } from '@/components/ui/toaster';
import { Metadata } from 'next';
import { Suspense } from 'react';

export const metadata: Metadata = {
  title: 'Personas',
  description: 'Generated by create next app',
};

export default function ElohimLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.ico" sizes="any" />
      </head>
      <body className="h-screen w-full">
        <Suspense>
          {children}
          <Toaster />
        </Suspense>
      </body>
    </html>
  );
}
