import { Toaster } from '@/components/ui/toaster';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Personas',
  description: 'Generated by create next app',
};

export default function ElohimLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.ico" sizes="any" />
      </head>
      <body className="flex flex-col h-screen w-full justify-center items-center">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
